### ISSUE TITLE
nix-opam-switch depends on jq

### ISSUE THREAD

**Issue by OlivierNicole** [Julow/nix-opam-switch#1]
Without jq, `nix-opam-switch list-available` fails. Maybe this dependency could be specified somewhere in the Nix files?

**Comment by Julow** [comment]
Thanks! Should be fixed.

The same bug happens with `nix-store` and `opam` but in this case is intended. I do not want to risk calling a different version of nix or opam than the version used by the user as they are both manipulating mutable stores.

**Comment by OlivierNicole** [comment]
Thanks!
